### ISSUE TITLE
Reconnecting to existing db fails intermittently

### ISSUE THREAD

**Issue by oneillal** [oneillal/FIMpy#2]
```~/dev/project/FIMpy/app(master*) » docker run -p 5000:5000 alanoneill/fimpy
Found local VCAP_SERVICES
Traceback (most recent call last):
  File "main.py", line 105, in <module>
    db = client.create_database(CONFIG['db_name'], throw_on_exists=False)
  File "/usr/local/lib/python2.7/dist-packages/cloudant/client.py", line 230, in create_database
    new_db.create()
  File "/usr/local/lib/python2.7/dist-packages/cloudant/database.py", line 348, in create
    resp.status_code, self.database_url, resp.text
cloudant.error.CloudantDatabaseException: Invalid database name during creation. Found: https://32c99717-667e-4413-9866-27be7c7eb9be-bluemix.cloudant.com/33e35b349486
```

**Comment by oneillal** [comment]
Still happening...seems to only be an issue when starting as a container.
